apiVersion: v2
name: kube-prometheus-stack
description: A Helm chart for kube-prometheus-stack

type: application
version: 1.0.0

dependencies:
- name: kube-prometheus-stack
  version: "3.0.8"
  repository: https://kubernetes-sigs.github.io/kube-prometheus-stack